name       : haskell-ieee754
version    : 0.8.0
release    : 1
source     :
    - http://hackage.haskell.org/package/ieee754-0.8.0/ieee754-0.8.0.tar.gz : 0e2dff9c37f59acf5c64f978ec320005e9830f276f9f314e4bfed3f482289ad1
license    : BSD-3-Clause
component  : programming.haskell
summary    : Utilities for dealing with IEEE floating point numbers, ported from the Tango math library; approximate and exact equality comparisons for general types.
description: |
    Utilities for dealing with IEEE floating point numbers, ported from the Tango math library; approximate and exact equality comparisons for general types.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
